final List<String> cities = [
  "Abbottabad, KPK",
  "Alipur, Punjab",
  "Attock, Punjab",
  "Bahawalnagar, Punjab",
  "Bahawalpur, Punjab",
  "Bannu, KPK",
  "Bhakkar, Punjab",
  "Burewala, Punjab",
  "Chakwal, Punjab",
  "Chaman, Balochistan",
  "Charsadda, KPK",
  "Chiniot, Punjab",
  "Chishtian, Punjab",
  "Dadu, Sindh",
  "Dera Ghazi Khan, Punjab",
  "Dera Ismail Khan, KPK",
  "Faisalabad, Punjab",
  "Gilgit, Gilgit-Baltistan",
  "Gojra, Punjab",
  "Gujranwala, Punjab",
  "Gujrat, Punjab",
  "Gwadar, Balochistan",
  "Hafizabad, Punjab",
  "Haripur, KPK",
  "Hasilpur, Punjab",
  "Hub, Balochistan",
  "Hyderabad, Sindh",
  "Islamabad, ICT",
  "Jacobabad, Sindh",
  "Jaranwala, Punjab",
  "Jhang, Punjab",
  "Jhelum, Punjab",
  "Kamoke, Punjab",
  "Karachi, Sindh",
  "Kasur, Punjab",
  "Khairpur, Sindh",
  "Khan Bela, Punjab",
  "Khanewal, Punjab",
  "Khanpur, Punjab",
  "Khushab, Punjab",
  "Khuzdar, Balochistan",
  "Kohat, KPK",
  "Kot Addu, Punjab",
  "Lahore, Punjab",
  "Larkana, Sindh",
  "Layyah, Punjab",
  "Lodhran, Punjab",
  "Mandi Bahauddin, Punjab",
  "Mansehra, KPK",
  "Mardan, KPK",
  "Mianwali, Punjab",
  "Mingora, KPK",
  "Mirpur Khas, Sindh",
  "Mirpur, Azad Kashmir",
  "Multan, Punjab",
  "Muridke, Punjab",
  "Muzaffarabad, Azad Kashmir",
  "Muzaffargarh, Punjab",
  "Nankana Sahib, Punjab",
  "Narowal, Punjab",
  "Nawabshah, Sindh",
  "Nowshera, KPK",
  "Okara, Punjab",
  "Pakpattan, Punjab",
  "Peshawar, KPK",
  "Quetta, Balochistan",
  "Rahim Yar Khan, Punjab",
  "Rawalpindi, Punjab",
  "Sadiqabad, Punjab",
  "Sahiwal, Punjab",
  "Sambrial, Punjab",
  "Sargodha, Punjab",
  "Shahdadkot, Sindh",
  "Sheikhupura, Punjab",
  "Shikarpur, Sindh",
  "Sialkot, Punjab",
  "Sukkur, Sindh",
  "Swabi, KPK",
  "Tando Adam, Sindh",
  "Tando Allahyar, Sindh",
  "Taxila, Punjab",
  "Toba Tek Singh, Punjab",
  "Turbat, Balochistan",
  "Vehari, Punjab",
  "Wah Cantt, Punjab",
  "Wazirabad, Punjab",
];
